# Use the official NGINX image as the base image
FROM nginx:alpine

# Copy the HTML file to the NGINX default directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to the public
EXPOSE 80